import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from './footer/page';
import ComponentWrapper from "./componentwrapper"; 

const myFont = localFont({
  src: '../../public/fonts/GuarujaNeue-Regular.otf',
  variable: '--font-GuarujaNeue'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <div className="text-white bg-[#0D0D0D]">
          <div>
            <ComponentWrapper /> {/* Use the NavbarWrapper here */}
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
